// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekat.Models;

namespace Projekat.Migrations
{
    [DbContext(typeof(PlanerContext))]
    partial class PlanerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Projekat.Models.Dan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Naziv");

                    b.Property<int?>("NedeljaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NedeljaID");

                    b.ToTable("Dani");
                });

            modelBuilder.Entity("Projekat.Models.Nedelja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.HasKey("ID");

                    b.ToTable("Planer");
                });

            modelBuilder.Entity("Projekat.Models.Obaveza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("Boja")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Boja");

                    b.Property<int?>("DanID")
                        .HasColumnType("int");

                    b.Property<int>("Hitno")
                        .HasColumnType("int")
                        .HasColumnName("Hitno");

                    b.Property<string>("Predmet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Predmet");

                    b.HasKey("ID");

                    b.HasIndex("DanID");

                    b.ToTable("Obaveze");
                });

            modelBuilder.Entity("Projekat.Models.Dan", b =>
                {
                    b.HasOne("Projekat.Models.Nedelja", "Nedelja")
                        .WithMany("Dani")
                        .HasForeignKey("NedeljaID");

                    b.Navigation("Nedelja");
                });

            modelBuilder.Entity("Projekat.Models.Obaveza", b =>
                {
                    b.HasOne("Projekat.Models.Dan", "Dan")
                        .WithMany("Obaveze")
                        .HasForeignKey("DanID");

                    b.Navigation("Dan");
                });

            modelBuilder.Entity("Projekat.Models.Dan", b =>
                {
                    b.Navigation("Obaveze");
                });

            modelBuilder.Entity("Projekat.Models.Nedelja", b =>
                {
                    b.Navigation("Dani");
                });
#pragma warning restore 612, 618
        }
    }
}
